/**
 * fetch-images.mjs — Build-time Unsplash curator.
 *
 * Fetches a curated set of cinematic images from the Unsplash API and writes
 * their public CDN URLs + attribution into `src/data/gallery.ts`.
 *
 * The Unsplash access key is used ONLY here, at build time. It is read from the
 * environment and is never committed or shipped to the browser. The generated
 * data file contains only public `images.unsplash.com` CDN URLs.
 *
 * Usage:
 *   UNSPLASH_ACCESS_KEY=xxx node scripts/fetch-images.mjs
 *
 * If no key is present the script exits quietly, leaving the committed
 * gallery.ts untouched (so CI builds without the key still succeed).
 */

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const KEY = process.env.UNSPLASH_ACCESS_KEY;
if (!KEY) {
  console.log('[fetch-images] No UNSPLASH_ACCESS_KEY set — keeping existing gallery.ts.');
  process.exit(0);
}

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(__dirname, '../src/data/gallery.ts');

/** Curated slots: each becomes a named export used across the UI. */
const SLOTS = [
  { key: 'hero', query: 'dark abstract technology neon' },
  { key: 'circuit', query: 'circuit board macro dark' },
  { key: 'grid', query: 'blue digital grid abstract' },
  { key: 'retro', query: 'retro arcade neon dark' },
  { key: 'code', query: 'green code terminal dark' },
];

async function pick(query) {
  const url = `https://api.unsplash.com/search/photos?query=${encodeURIComponent(
    query,
  )}&per_page=1&orientation=landscape&content_filter=high&client_id=${KEY}`;
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Unsplash ${res.status} for "${query}"`);
  const data = await res.json();
  const p = data.results?.[0];
  if (!p) throw new Error(`No result for "${query}"`);
  const base = p.urls.raw.split('?')[0];
  return {
    base,
    author: p.user.name,
    authorUrl: p.user.links.html,
    alt: p.alt_description || query,
  };
}

const entries = {};
for (const slot of SLOTS) {
  entries[slot.key] = await pick(slot.query);
  console.log(`[fetch-images] ${slot.key} -> ${entries[slot.key].base}`);
}

const body = `/**
 * gallery.ts — AUTO-GENERATED by scripts/fetch-images.mjs
 *
 * Curated cinematic imagery from Unsplash. These are public CDN base URLs;
 * call \`img(base, width)\` to request an optimized, auto-formatted variant.
 * Photographer attribution is included per the Unsplash API guidelines.
 */

export interface GalleryImage {
  base: string;
  author: string;
  authorUrl: string;
  alt: string;
}

/** Build an optimized Unsplash CDN URL at the requested width. */
export function img(base: string, width = 2400): string {
  return \`\${base}?auto=format&fit=crop&q=80&w=\${width}\`;
}

export const GALLERY: Record<string, GalleryImage> = ${JSON.stringify(entries, null, 2)};
`;

await writeFile(OUT, body, 'utf8');
console.log(`[fetch-images] Wrote ${OUT}`);
