/**
 * gallery.ts — AUTO-GENERATED by scripts/fetch-images.mjs
 *
 * Curated cinematic imagery from Unsplash. These are public CDN base URLs;
 * call `img(base, width)` to request an optimized, auto-formatted variant.
 * Photographer attribution is included per the Unsplash API guidelines.
 */

export interface GalleryImage {
  base: string;
  author: string;
  authorUrl: string;
  alt: string;
}

/** Build an optimized Unsplash CDN URL at the requested width. */
export function img(base: string, width = 2400): string {
  return `${base}?auto=format&fit=crop&q=80&w=${width}`;
}

export const GALLERY: Record<string, GalleryImage> = {
  "hero": {
    "base": "https://images.unsplash.com/photo-1771875797242-77f69f061132",
    "author": "Liana S",
    "authorUrl": "https://unsplash.com/@cherstve_pechivo",
    "alt": "Streaks of purple and green lights against dark background"
  },
  "circuit": {
    "base": "https://images.unsplash.com/photo-1767549707419-ceef47ff370d",
    "author": "K. K.",
    "authorUrl": "https://unsplash.com/@korner_kosmos",
    "alt": "Vintage nixie tube clock displays glowing orange numbers."
  },
  "grid": {
    "base": "https://images.unsplash.com/photo-1683064325134-3acfdef9c6d7",
    "author": "Visax",
    "authorUrl": "https://unsplash.com/@visaxslr",
    "alt": "an abstract blue background with wavy lines"
  },
  "retro": {
    "base": "https://images.unsplash.com/photo-1511512578047-dfb367046420",
    "author": "Carl Raw",
    "authorUrl": "https://unsplash.com/@carltraw",
    "alt": "gaming room with arcade machines"
  },
  "code": {
    "base": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5",
    "author": "Markus Spiske",
    "authorUrl": "https://unsplash.com/@markusspiske",
    "alt": "Matrix movie still"
  }
};
